controller_list:
  - name: fake_hebi_arm_controller
    joints:
      - HEBI/base/X8_9
      - HEBI/shoulder/X8_16
      - HEBI/elbow/X8_9
      - HEBI/wrist1/X5_1
      - HEBI/wrist2/X5_1
      - HEBI/wrist3/X5_1
  - name: fake_hand_controller
    joints:
      - end_effector/input_l_finger