# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - Arm/J1_base/X8_9
    - Arm/J2_shoulder/X8_16
    - Arm/J3_elbow/X8_9
    - Arm/J4_wrist1/X5_1
    - Arm/J5_wrist2/X5_1
    - Arm/J6_wrist3/X5_1
    - end_effector/input_l_finger
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: hebi_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - Arm/J1_base/X8_9
      - Arm/J2_shoulder/X8_16
      - Arm/J3_elbow/X8_9
      - Arm/J4_wrist1/X5_1
      - Arm/J5_wrist2/X5_1
      - Arm/J6_wrist3/X5_1
  - name: hand_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - end_effector/input_l_finger
