controller_list:
  - name: fake_hebi_arm_controller
    joints:
      - Arm/J1_base
      - Arm/J2_shoulder
      - Arm/J3_elbow
      - Arm/J4_wrist1
      - Arm/J5_wrist2
  - name: fake_hand_controller
    joints:
      - end_effector/input_l_finger
initial:  # Define initial robot poses.
  - group: hebi_arm
    pose: home
  - group: hand
    pose: open