# Default initial positions for A-2085-04's ros2_control fake system
initial_positions:
  J1_base: 0
  J2_shoulder: 0
  J3_elbow: 0
  J4_wrist: 0

# Initial position for the arm when use_mock_hardware is false
home_position: "0.0;2.09;2.09;0.0"

families: "Arm"

names: "J1_base;J2_shoulder;J3_elbow;J4_wrist"

hrdf_pkg: "hebi_description"
hrdf_file: "config/hrdf/A-2085-04.hrdf"
gains_pkg: "hebi_description"
gains_file: "config/gains/A-2085-04_gains.xml"

use_mock_hardware: true
use_gazebo: false