controller_list:
  - name: fake_hebi_arm_controller
    joints:
      - Arm/J1_base
      - Arm/J2_shoulder
      - Arm/J3_elbow
      - Arm/J4_wrist1
  - name: fake_hand_controller
    joints:
      - end_effector/input_l_finger
